/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MalagaRouteImport } from './routes/malaga'
import { Route as IndexRouteImport } from './routes/index'

const MalagaRoute = MalagaRouteImport.update({
  id: '/malaga',
  path: '/malaga',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/malaga': typeof MalagaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/malaga': typeof MalagaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/malaga': typeof MalagaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/malaga'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/malaga'
  id: '__root__' | '/' | '/malaga'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MalagaRoute: typeof MalagaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/malaga': {
      id: '/malaga'
      path: '/malaga'
      fullPath: '/malaga'
      preLoaderRoute: typeof MalagaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MalagaRoute: MalagaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
